apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubetes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/yuvakkrishnan/kubetes-config.git'
    targetRevision: main
    path: helm/kubetes
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
